<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>sn.snk</AssemblyOriginatorKeyFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/dotnetprojects/WpfExtendedToolkit</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dotnetprojects/WpfExtendedToolkit</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <Authors>DotNetProjects</Authors>
    <!--<PackageId>DotNetProjects.Extended.Wpf.Toolkit</PackageId>-->
    <Version>1.1.1</Version>
    <AssemblyVersion>1.1.1.0</AssemblyVersion>
    <FileVersion>1.1.1.0</FileVersion>
    <RootNamespace>Xceed.Wpf.Toolkit</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Quicker.Extended.Wpf.Toolkit</PackageId>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EnableSourceLink>true</EnableSourceLink>
  </PropertyGroup>


  <ItemGroup>
    <Resource Include="**\*.png" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Zoombox\Resources\Zoom.cur" />
    <None Remove="Zoombox\Resources\ZoomRelative.cur" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Zoombox\Resources\Zoom.cur" />
    <Resource Include="Zoombox\Resources\ZoomRelative.cur" />
  </ItemGroup>
</Project>